version: "3.9"

services:
  brute-force-protection:
    build: .
    ports:
      - 9001:9001
    depends_on:
      - postgres
    entrypoint: bash -c '
      until `((echo > /dev/tcp/postgres/5432) >/dev/null 2>&1)`; do sleep 1; done && ls -lah &&
      ./brute_force_protection .env.local migrate && ./brute_force_protection .env.local'

  postgres:
    image: postgres:buster
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 2345:5432