version: "3.9"

services:
  brute-force-protection:
    build: .
    ports:
      - 9001:9001
    environment:
      RPC_PORT: :9001
      TECHNICAL_API_PORT: :8021
      PROFILING_API_PORT: :6062
      LOG_LEVEL: DEBUG
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
    entrypoint: bash -c '
      until `((echo > /dev/tcp/postgres/5432) >/dev/null 2>&1)`; do sleep 1; done &&
      ./brute_force_protection'

  postgres:
    image: postgres:buster
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password