// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: contract/protector.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestAuthAttempt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login     string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	IpAddress string `protobuf:"bytes,3,opt,name=IpAddress,proto3" json:"IpAddress,omitempty"`
}

func (x *RequestAuthAttempt) Reset() {
	*x = RequestAuthAttempt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_protector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAuthAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAuthAttempt) ProtoMessage() {}

func (x *RequestAuthAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAuthAttempt.ProtoReflect.Descriptor instead.
func (*RequestAuthAttempt) Descriptor() ([]byte, []int) {
	return file_contract_protector_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAuthAttempt) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RequestAuthAttempt) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RequestAuthAttempt) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type ResponseAuthAttempt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed  bool   `protobuf:"varint,1,opt,name=Allowed,proto3" json:"Allowed,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
}

func (x *ResponseAuthAttempt) Reset() {
	*x = ResponseAuthAttempt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_protector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAuthAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAuthAttempt) ProtoMessage() {}

func (x *ResponseAuthAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAuthAttempt.ProtoReflect.Descriptor instead.
func (*ResponseAuthAttempt) Descriptor() ([]byte, []int) {
	return file_contract_protector_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseAuthAttempt) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *ResponseAuthAttempt) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RequestCleanBucketByLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
}

func (x *RequestCleanBucketByLogin) Reset() {
	*x = RequestCleanBucketByLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_protector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCleanBucketByLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCleanBucketByLogin) ProtoMessage() {}

func (x *RequestCleanBucketByLogin) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCleanBucketByLogin.ProtoReflect.Descriptor instead.
func (*RequestCleanBucketByLogin) Descriptor() ([]byte, []int) {
	return file_contract_protector_proto_rawDescGZIP(), []int{2}
}

func (x *RequestCleanBucketByLogin) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type ResponseCleanBucketByLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
}

func (x *ResponseCleanBucketByLogin) Reset() {
	*x = ResponseCleanBucketByLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_protector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCleanBucketByLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCleanBucketByLogin) ProtoMessage() {}

func (x *ResponseCleanBucketByLogin) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCleanBucketByLogin.ProtoReflect.Descriptor instead.
func (*ResponseCleanBucketByLogin) Descriptor() ([]byte, []int) {
	return file_contract_protector_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseCleanBucketByLogin) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RequestCleanBucketByIp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpAddress string `protobuf:"bytes,1,opt,name=IpAddress,proto3" json:"IpAddress,omitempty"`
}

func (x *RequestCleanBucketByIp) Reset() {
	*x = RequestCleanBucketByIp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_protector_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCleanBucketByIp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCleanBucketByIp) ProtoMessage() {}

func (x *RequestCleanBucketByIp) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protector_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCleanBucketByIp.ProtoReflect.Descriptor instead.
func (*RequestCleanBucketByIp) Descriptor() ([]byte, []int) {
	return file_contract_protector_proto_rawDescGZIP(), []int{4}
}

func (x *RequestCleanBucketByIp) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type ResponseCleanBucketByIp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
}

func (x *ResponseCleanBucketByIp) Reset() {
	*x = ResponseCleanBucketByIp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_protector_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCleanBucketByIp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCleanBucketByIp) ProtoMessage() {}

func (x *ResponseCleanBucketByIp) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protector_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCleanBucketByIp.ProtoReflect.Descriptor instead.
func (*ResponseCleanBucketByIp) Descriptor() ([]byte, []int) {
	return file_contract_protector_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseCleanBucketByIp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RequestAddToList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubnetAddress string `protobuf:"bytes,1,opt,name=SubnetAddress,proto3" json:"SubnetAddress,omitempty"`
}

func (x *RequestAddToList) Reset() {
	*x = RequestAddToList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_protector_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAddToList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddToList) ProtoMessage() {}

func (x *RequestAddToList) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protector_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddToList.ProtoReflect.Descriptor instead.
func (*RequestAddToList) Descriptor() ([]byte, []int) {
	return file_contract_protector_proto_rawDescGZIP(), []int{6}
}

func (x *RequestAddToList) GetSubnetAddress() string {
	if x != nil {
		return x.SubnetAddress
	}
	return ""
}

type ResponseAddToList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
}

func (x *ResponseAddToList) Reset() {
	*x = ResponseAddToList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_protector_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAddToList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAddToList) ProtoMessage() {}

func (x *ResponseAddToList) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protector_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAddToList.ProtoReflect.Descriptor instead.
func (*ResponseAddToList) Descriptor() ([]byte, []int) {
	return file_contract_protector_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseAddToList) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RequestRemoveFromList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubnetAddress string `protobuf:"bytes,1,opt,name=SubnetAddress,proto3" json:"SubnetAddress,omitempty"`
}

func (x *RequestRemoveFromList) Reset() {
	*x = RequestRemoveFromList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_protector_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRemoveFromList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRemoveFromList) ProtoMessage() {}

func (x *RequestRemoveFromList) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protector_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRemoveFromList.ProtoReflect.Descriptor instead.
func (*RequestRemoveFromList) Descriptor() ([]byte, []int) {
	return file_contract_protector_proto_rawDescGZIP(), []int{8}
}

func (x *RequestRemoveFromList) GetSubnetAddress() string {
	if x != nil {
		return x.SubnetAddress
	}
	return ""
}

type ResponseRemoveFromList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
}

func (x *ResponseRemoveFromList) Reset() {
	*x = ResponseRemoveFromList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_protector_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRemoveFromList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRemoveFromList) ProtoMessage() {}

func (x *ResponseRemoveFromList) ProtoReflect() protoreflect.Message {
	mi := &file_contract_protector_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRemoveFromList.ProtoReflect.Descriptor instead.
func (*ResponseRemoveFromList) Descriptor() ([]byte, []int) {
	return file_contract_protector_proto_rawDescGZIP(), []int{9}
}

func (x *ResponseRemoveFromList) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_contract_protector_proto protoreflect.FileDescriptor

var file_contract_protector_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x22, 0x64, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41,
	0x75, 0x74, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4b, 0x0a, 0x13, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x75, 0x74, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x31, 0x0a, 0x19, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x79, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x38, 0x0a, 0x1a, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x42, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x36, 0x0a, 0x16, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43,
	0x6c, 0x65, 0x61, 0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x79, 0x49, 0x70, 0x12, 0x1c,
	0x0a, 0x09, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x17,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x42, 0x79, 0x49, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x22, 0x38, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x64,
	0x64, 0x54, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x2f, 0x0a,
	0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x3d,
	0x0a, 0x15, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x34, 0x0a,
	0x16, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x32, 0xe8, 0x04, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x4c, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74,
	0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x41, 0x75, 0x74, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x1a, 0x1d,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x41, 0x75, 0x74, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x22, 0x00, 0x12,
	0x61, 0x0a, 0x12, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x79,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x42, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x24, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c,
	0x65, 0x61, 0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x22, 0x00, 0x12, 0x58, 0x0a, 0x0f, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x42, 0x79, 0x49, 0x70, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x42, 0x79, 0x49, 0x70, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x6e,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x79, 0x49, 0x70, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0e,
	0x41, 0x64, 0x64, 0x54, 0x6f, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64,
	0x64, 0x54, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x13, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4c, 0x69, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x57, 0x68,
	0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x00, 0x12, 0x5a, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2e, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contract_protector_proto_rawDescOnce sync.Once
	file_contract_protector_proto_rawDescData = file_contract_protector_proto_rawDesc
)

func file_contract_protector_proto_rawDescGZIP() []byte {
	file_contract_protector_proto_rawDescOnce.Do(func() {
		file_contract_protector_proto_rawDescData = protoimpl.X.CompressGZIP(file_contract_protector_proto_rawDescData)
	})
	return file_contract_protector_proto_rawDescData
}

var file_contract_protector_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_contract_protector_proto_goTypes = []interface{}{
	(*RequestAuthAttempt)(nil),         // 0: contract.RequestAuthAttempt
	(*ResponseAuthAttempt)(nil),        // 1: contract.ResponseAuthAttempt
	(*RequestCleanBucketByLogin)(nil),  // 2: contract.RequestCleanBucketByLogin
	(*ResponseCleanBucketByLogin)(nil), // 3: contract.ResponseCleanBucketByLogin
	(*RequestCleanBucketByIp)(nil),     // 4: contract.RequestCleanBucketByIp
	(*ResponseCleanBucketByIp)(nil),    // 5: contract.ResponseCleanBucketByIp
	(*RequestAddToList)(nil),           // 6: contract.RequestAddToList
	(*ResponseAddToList)(nil),          // 7: contract.ResponseAddToList
	(*RequestRemoveFromList)(nil),      // 8: contract.RequestRemoveFromList
	(*ResponseRemoveFromList)(nil),     // 9: contract.ResponseRemoveFromList
}
var file_contract_protector_proto_depIdxs = []int32{
	0, // 0: contract.Protector.AuthAttempt:input_type -> contract.RequestAuthAttempt
	2, // 1: contract.Protector.CleanBucketByLogin:input_type -> contract.RequestCleanBucketByLogin
	4, // 2: contract.Protector.CleanBucketByIP:input_type -> contract.RequestCleanBucketByIp
	6, // 3: contract.Protector.AddToBlackList:input_type -> contract.RequestAddToList
	8, // 4: contract.Protector.RemoveFromBlackList:input_type -> contract.RequestRemoveFromList
	6, // 5: contract.Protector.AddToWhiteList:input_type -> contract.RequestAddToList
	8, // 6: contract.Protector.RemoveFromWhiteList:input_type -> contract.RequestRemoveFromList
	1, // 7: contract.Protector.AuthAttempt:output_type -> contract.ResponseAuthAttempt
	3, // 8: contract.Protector.CleanBucketByLogin:output_type -> contract.ResponseCleanBucketByLogin
	5, // 9: contract.Protector.CleanBucketByIP:output_type -> contract.ResponseCleanBucketByIp
	7, // 10: contract.Protector.AddToBlackList:output_type -> contract.ResponseAddToList
	9, // 11: contract.Protector.RemoveFromBlackList:output_type -> contract.ResponseRemoveFromList
	7, // 12: contract.Protector.AddToWhiteList:output_type -> contract.ResponseAddToList
	9, // 13: contract.Protector.RemoveFromWhiteList:output_type -> contract.ResponseRemoveFromList
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_protector_proto_init() }
func file_contract_protector_proto_init() {
	if File_contract_protector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contract_protector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAuthAttempt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_protector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAuthAttempt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_protector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCleanBucketByLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_protector_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCleanBucketByLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_protector_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCleanBucketByIp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_protector_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCleanBucketByIp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_protector_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAddToList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_protector_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAddToList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_protector_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRemoveFromList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_protector_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRemoveFromList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contract_protector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_protector_proto_goTypes,
		DependencyIndexes: file_contract_protector_proto_depIdxs,
		MessageInfos:      file_contract_protector_proto_msgTypes,
	}.Build()
	File_contract_protector_proto = out.File
	file_contract_protector_proto_rawDesc = nil
	file_contract_protector_proto_goTypes = nil
	file_contract_protector_proto_depIdxs = nil
}
